from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_pdf_report(output_path, summary, clause_results):
    """
    Generates a PDF risk report.

    output_path: path to save the PDF
    summary: {
        "total_clauses": int,
        "high": int,
        "medium": int,
        "low": int,
        "overall_risk": str
    }
    clause_results: list of {
        "clause_index": int,
        "text": str,
        "risk": {
            "risk_level": str,
            "issue": str,
            "explanation": str,
            "suggested_rewrite": str
        }
    }
    """

    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER

    # ------------------------------------------------------
    # COVER PAGE
    # ------------------------------------------------------
    c.setFont("Helvetica-Bold", 24)
    c.drawString(72, height - 100, "Contract Clause Risk Report")

    c.setFont("Helvetica", 14)
    c.drawString(72, height - 130, "Generated by Contract Risk Analyzer")
    c.drawString(72, height - 150, f"Date: {datetime.now().strftime('%Y-%m-%d')}")

    c.showPage()

    # ------------------------------------------------------
    # EXECUTIVE SUMMARY
    # ------------------------------------------------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(72, height - 72, "Executive Summary")

    c.setFont("Helvetica", 12)
    y = height - 120

    lines = [
        f"Total Clauses: {summary['total_clauses']}",
        f"High Risk: {summary['high']}",
        f"Medium Risk: {summary['medium']}",
        f"Low Risk: {summary['low']}",
        f"Overall Risk Rating: {summary['overall_risk']}",
    ]

    for line in lines:
        c.drawString(72, y, line)
        y -= 20

    c.showPage()

    # ------------------------------------------------------
    # DETAILED CLAUSE ANALYSIS
    # ------------------------------------------------------
    for item in clause_results:
        c.setFont("Helvetica-Bold", 16)
        c.drawString(72, height - 72, f"Clause {item['clause_index']}")

        risk = item.get("risk", {})
        y = height - 110

        c.setFont("Helvetica", 12)
        c.drawString(72, y, f"Risk Level: {risk.get('risk_level', 'UNKNOWN')}")
        y -= 20

        c.drawString(72, y, f"Issue: {risk.get('issue', '-')}")
        y -= 20

        # Explanation
        c.drawString(72, y, "Explanation:")
        y -= 20

        explanation = risk.get("explanation", "-")
        for line in explanation.split("\n"):
            c.drawString(90, y, line.strip())
            y -= 15
            if y < 72:
                c.showPage()
                y = height - 72

        y -= 10
        c.drawString(72, y, "Suggested Rewrite:")
        y -= 20

        rewrite = risk.get("suggested_rewrite", "-")
        for line in rewrite.split("\n"):
            c.drawString(90, y, line.strip())
            y -= 15
            if y < 72:
                c.showPage()
                y = height - 72

        y -= 20
        c.drawString(72, y, "Original Clause:")
        y -= 20

        clause_text = item.get("text", "-")
        for line in clause_text.split("\n"):
            c.drawString(90, y, line.strip())
            y -= 15
            if y < 72:
                c.showPage()
                y = height - 72

        c.showPage()

    # ------------------------------------------------------
    # FINALIZE PDF
    # ------------------------------------------------------
    c.save()
